;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Mar 29 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================
.CSEG
BCDTo7seg: .DB  0x7e, 0x30, 0x6d, 0x79, 0x33, 0x5b, 0x5f, 0x70, 0x7f, 0x7b
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================
RESET:
      ldi r16, high(RAMEND)  
      out SPH, r16
      ldi r16, low(RAMEND)
      out SPL, r16
      ldi r18, 0xff ;for loop
      ldi r19, 0xff ;for loop
      ldi r20, 0x0b ;count for 10 numbers
      ldi r16, 0x7d
      out DDRB, r16
      ldi ZH, high(BCDTo7seg)
      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; Write your code here
      dec r20
      breq end
      lpm r17, Z+
      out PORTB, r17
      rjmp loop
      
loop:
      nop
      dec r18
      inc r18
      nop
      dec r18
      inc r18
      nop
      dec r18
      brne loop
      
      nop
      dec r19
      inc r19
      nop
      dec r19
      inc r19
      nop
      dec r19
      brne loop
      
      ldi r18, 0xff
      nop
      dec r18
      inc r18
      nop
      dec r18
      brne start
      

end:
      rjmp end
;====================================================================

