;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Mar 29 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================
.CSEG
BCDTo7seg: .DB  0x7e, 0x30, 0x6d, 0x79, 0x33, 0x5b, 0x5f, 0x70, 0x7f, 0x7b
;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================
RESET:
      ldi r16, high(RAMEND)  
      out SPH, r16
      ldi r16, low(RAMEND)
      out SPL, r16
      ldi r18, 0xff
      ldi r16, 0x7d
      out DDRB, r16
      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; Write your code here
      ldi ZH, high(BCDTo7seg)
      lpm r17, Z+
      out PORTB, r17
      
      ;lpm r17, Z+
      ;out PORTB, r17
      rjmp end
Loop:
      dec r18
      cpse r18, r19
      rjmp  Loop
      ldi r18, 0xff
      rjmp Start

end:
      rjmp end
;====================================================================
