;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Mar 28 2017
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================
Reset:
      ldi r16, high(RAMEND)  
      out SPH, r16
      ldi r16, low(RAMEND)
      out SPL, r16
      ; Reset Vector
      
      rjmp  Start
      
;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; Write your code here
      ldi r16, 0x09
      mov r10, r16
      ldi r16, 0x00 ;inccrements (5)
      ldi r17, 0x05 ;just storing the value of 5 till the end
      ldi r18, 0x00 ;initialization
      ldi r19, 0x00 ;initialization
Loop:
      add r16, r17
      cp r10, r16
      brcs end ;if r16 > r10
      mul r16, r16 ;the result will be stored in r0, r1
      add r18, r0
      adc r19, r1
      movw r0, r18
      rjmp  Loop

;====================================================================

end:
   rjmp end

   